# Student Performance Management and Analysis System

**Project Title:** Student Performance Management and Analysis System

**Business Scenario:** A small training institute currently maintains student records manually. This notebook builds a beginner-friendly Python solution to store student details in a CSV file, calculate performance metrics, and generate summary reports using core Python, NumPy, and Pandas.

This notebook solves **Tasks 1–15** in sequence. Each task includes:
- **Problem Statement** — what is being asked
- **Approach** — how we solve it
- A **commented code cell** with the implementation and output

## Task 1: Basic Python Operations

**Problem Statement:** Store one student's details (name, age, city, course, marks, attendance) in variables and print them in a clean, readable format.

**Approach:** Create simple Python variables of appropriate data types (string, int) for each attribute, then use an f-string to print them in the required layout.

In [1]:
# Store individual student details in separate variables
student_name = "Rahul"          # string - student's name
age = 22                        # int - student's age
city = "Patna"                  # string - student's city
course = "Python"               # string - enrolled course
marks = 85                      # int - marks obtained out of 100
attendance_percentage = 92      # int - attendance percentage

# Print details in a clean, labeled format using f-strings
print(f"Student Name: {student_name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Course: {course}")
print(f"Marks: {marks}")
print(f"Attendance: {attendance_percentage}%")

Student Name: Rahul
Age: 22
City: Patna
Course: Python
Marks: 85
Attendance: 92%

## Task 2: Conditional Statement

**Problem Statement:** Decide Pass/Fail based on marks (>=40 = Pass) and assign a Grade based on marks ranges (A+, A, B, C, Fail).

**Approach:** Use `if-elif-else` chains inside two functions — one to check pass/fail, another to map marks to a grade band. Testing top-down from the highest threshold ensures correct bucket assignment.

In [2]:
def get_result(marks):
    return "Pass" if marks >= 40 else "Fail"

def get_grade(marks):
    if marks >= 90:
        return "A+"
    elif marks >= 75:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 40:
        return "C"
    else:
        return "Fail"

print(f"Result: {get_result(marks)}")
print(f"Grade: {get_grade(marks)}")

Result: Pass
Grade: A

## Task 3: Loops

**Problem Statement:** Given a list of marks, print each value, count passes/fails, and compute highest, lowest, total, and average marks.

**Approach:** Iterate through the list once with a `for` loop, updating running counters (`passed_count`, `failed_count`, `total`) and tracking variables (`highest`, `lowest`) as we go, reinforcing manual loop logic instead of relying on built-ins.

In [3]:
marks_list = [85, 92, 76, 88, 69, 91, 55, 78, 39, 95]

print("All marks:")
for m in marks_list:
    print(m)

passed_count = 0
failed_count = 0
for m in marks_list:
    if m >= 40:
        passed_count += 1
    else:
        failed_count += 1

highest = marks_list[0]
lowest = marks_list[0]
total = 0
for m in marks_list:
    if m > highest:
        highest = m
    if m < lowest:
        lowest = m
    total += m

average = total / len(marks_list)

print(f"\nPassed Students: {passed_count}")
print(f"Failed Students: {failed_count}")
print(f"Highest Marks: {highest}")
print(f"Lowest Marks: {lowest}")
print(f"Total Marks: {total}")
print(f"Average Marks: {average}")

All marks:
85
92
76
88
69
91
55
78
39
95

Passed Students: 9
Failed Students: 1
Highest Marks: 95
Lowest Marks: 39
Total Marks: 768
Average Marks: 76.8

## Task 4: Data Structures

**Problem Statement:** Demonstrate list, tuple, set, and dictionary with typical operations relevant to the student dataset.

**Approach:**
- **List** (mutable, ordered) → student names, add/remove entries.
- **Tuple** (immutable, ordered) → fixed course names, access by index.
- **Set** (unordered, unique) → cities, add/remove/de-duplication.
- **Dictionary** (key-value) → one full student record, access/update/add key.

### List

In [4]:
student_names = ["Rahul", "Priya", "Aman", "Neha", "Rohan"]

student_names.append("Sneha")
print("After adding Sneha:", student_names)

student_names.remove("Aman")
print("After removing Aman:", student_names)

print("\nAll student names:")
for name in student_names:
    print(name)

After adding Sneha: ['Rahul', 'Priya', 'Aman', 'Neha', 'Rohan', 'Sneha']
After removing Aman: ['Rahul', 'Priya', 'Neha', 'Rohan', 'Sneha']

All student names:
Rahul
Priya
Neha
Rohan
Sneha

### Tuple

In [5]:
courses = ("Python", "Data Science", "Analytics")

print("All courses:")
for c in courses:
    print(c)

print("\nSecond course:", courses[1])

All courses:
Python
Data Science
Analytics

Second course: Data Science

### Set

In [6]:
cities = {"Patna", "Delhi", "Kolkata", "Mumbai"}
print("Unique cities:", cities)

cities.add("Bangalore")
print("After adding Bangalore:", cities)

cities.remove("Bangalore")
print("After removing Bangalore:", cities)

Unique cities: {'Kolkata', 'Patna', 'Delhi', 'Mumbai'}
After adding Bangalore: {'Kolkata', 'Bangalore', 'Patna', 'Mumbai', 'Delhi'}
After removing Bangalore: {'Kolkata', 'Patna', 'Mumbai', 'Delhi'}

### Dictionary

In [7]:
student_dict = {
    "Student_ID": 1,
    "Name": "Rahul",
    "Age": 22,
    "City": "Patna",
    "Course": "Python",
    "Marks": 85,
    "Attendance_Percentage": 92
}

print("Student Name:", student_dict["Name"])

student_dict["Marks"] = 90
print("Updated Marks:", student_dict["Marks"])

student_dict["Result"] = "Pass"

print("\nAll keys and values:")
for key, value in student_dict.items():
    print(f"{key}: {value}")

Student Name: Rahul
Updated Marks: 90

All keys and values:
Student_ID: 1
Name: Rahul
Age: 22
City: Patna
Course: Python
Marks: 90
Attendance_Percentage: 92
Result: Pass

## Task 5: Functions

**Problem Statement:** Wrap the result, grade, average, and attendance-status logic into reusable functions.

**Approach:** Define four standalone functions, each with a single responsibility, making the logic reusable later in Pandas (`.apply()`) and testable in isolation.

In [8]:
def calculate_result(marks):
    """Return 'Pass' if marks >= 40, else 'Fail'."""
    return "Pass" if marks >= 40 else "Fail"

def calculate_grade(marks):
    """Map marks to a letter grade band."""
    if marks >= 90:
        return "A+"
    elif marks >= 75:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 40:
        return "C"
    else:
        return "Fail"

def calculate_average(marks_list):
    """Return the average of a list of marks."""
    return sum(marks_list) / len(marks_list)

def check_attendance_status(attendance):
    """Return 'Eligible' if attendance >= 75, else 'Low Attendance'."""
    return "Eligible" if attendance >= 75 else "Low Attendance"

print(calculate_result(85))
print(calculate_grade(85))
print(calculate_average([85, 92, 76, 88, 69]))
print(check_attendance_status(72))

Pass
A
82.0
Low Attendance

## Task 6: Error Handling

**Problem Statement:** Accept marks as user input and handle non-numeric text, marks < 0, and marks > 100 without crashing.

**Approach:** Use `try/except` to catch `ValueError` on `float()` conversion, plus an `if` range check inside `try`. Loop with `while True` to re-prompt until valid. Since `input()` blocks notebook execution, we demonstrate with simulated inputs.

In [9]:
def get_valid_marks():
    """Interactive version - repeatedly prompts until valid marks are entered."""
    while True:
        user_input = input("Enter marks (0-100): ")
        try:
            marks = float(user_input)
            if marks < 0 or marks > 100:
                print("Invalid input. Please enter marks between 0 and 100.")
                continue
            return marks
        except ValueError:
            print("Invalid input. Please enter marks between 0 and 100.")

def validate_marks(user_input):
    """Non-interactive version for demonstration/testing with fixed inputs."""
    try:
        marks = float(user_input)
        if marks < 0 or marks > 100:
            return "Invalid input. Please enter marks between 0 and 100."
        return f"Valid marks entered: {marks}"
    except ValueError:
        return "Invalid input. Please enter marks between 0 and 100."

test_inputs = ["85", "abc", "-5", "150", "76.5"]
for inp in test_inputs:
    print(f"Input: {inp!r} -> {validate_marks(inp)}")

# To take real interactive input, uncomment below:
# marks = get_valid_marks()
# print("Marks accepted:", marks)

Input: '85' -> Valid marks entered: 85.0
Input: 'abc' -> Invalid input. Please enter marks between 0 and 100.
Input: '-5' -> Invalid input. Please enter marks between 0 and 100.
Input: '150' -> Invalid input. Please enter marks between 0 and 100.
Input: '76.5' -> Valid marks entered: 76.5

## Dataset Setup

**Problem Statement:** Tasks 7 onward need a shared 10-record dataset.

**Approach:** Define the dataset once as a list of lists plus a header, reused across the remaining tasks to avoid duplication.

In [10]:
import csv

students_data = [
    [1, "Rahul", 22, "Patna", "Python", 85, 92],
    [2, "Priya", 24, "Delhi", "Data Science", 92, 88],
    [3, "Aman", 21, "Kolkata", "Python", 76, 81],
    [4, "Neha", 23, "Mumbai", "Analytics", 88, 95],
    [5, "Rohan", 25, "Patna", "Python", 69, 72],
    [6, "Simran", 22, "Delhi", "Data Science", 91, 89],
    [7, "Vikash", 24, "Patna", "Analytics", 55, 68],
    [8, "Pooja", 21, "Kolkata", "Python", 78, 84],
    [9, "Arjun", 23, "Mumbai", "Data Science", 39, 60],
    [10, "Sneha", 22, "Delhi", "Python", 95, 97],
]

header = ["Student_ID", "Name", "Age", "City", "Course", "Marks", "Attendance_Percentage"]

## Task 8: CSV File Handling

**Problem Statement:** Create `students.csv`, then read it back and print each row.

**Approach:** Use `csv.writer` to write header + rows, `csv.reader` to read and iterate line by line.

In [11]:
with open("students.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(students_data)

print("students.csv created successfully.\n")

print("Reading students.csv:")
with open("students.csv", "r") as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

students.csv created successfully.

Reading students.csv:
['Student_ID', 'Name', 'Age', 'City', 'Course', 'Marks', 'Attendance_Percentage']
['1', 'Rahul', '22', 'Patna', 'Python', '85', '92']
['2', 'Priya', '24', 'Delhi', 'Data Science', '92', '88']
['3', 'Aman', '21', 'Kolkata', 'Python', '76', '81']
['4', 'Neha', '23', 'Mumbai', 'Analytics', '88', '95']
['5', 'Rohan', '25', 'Patna', 'Python', '69', '72']
['6', 'Simran', '22', 'Delhi', 'Data Science', '91', '89']
['7', 'Vikash', '24', 'Patna', 'Analytics', '55', '68']
['8', 'Pooja', '21', 'Kolkata', 'Python', '78', '84']
['9', 'Arjun', '23', 'Mumbai', 'Data Science', '39', '60']
['10', 'Sneha', '22', 'Delhi', 'Python', '95', '97']

## Task 7: File Handling

**Problem Statement:** Write a text summary (totals, average, highest/lowest, pass/fail counts) into `student_summary.txt`, then read and display it.

**Approach:** Compute stats with list comprehensions and built-ins (`sum`, `max`, `min`), format into a multi-line string, and use standard file I/O with `with` statements.

In [12]:
all_marks = [row[5] for row in students_data]

total_students = len(students_data)
avg_marks = sum(all_marks) / total_students
highest_marks = max(all_marks)
lowest_marks = min(all_marks)
passed_students = sum(1 for m in all_marks if m >= 40)
failed_students = total_students - passed_students

summary_text = f"""Student Performance Summary
Total Students: {total_students}
Average Marks: {round(avg_marks, 1)}
Highest Marks: {highest_marks}
Lowest Marks: {lowest_marks}
Passed Students: {passed_students}
Failed Students: {failed_students}
"""

with open("student_summary.txt", "w") as f:
    f.write(summary_text)

print("student_summary.txt created successfully.\n")

print("Reading student_summary.txt:")
with open("student_summary.txt", "r") as f:
    print(f.read())

student_summary.txt created successfully.

Reading student_summary.txt:
Student Performance Summary
Total Students: 10
Average Marks: 76.8
Highest Marks: 95
Lowest Marks: 39
Passed Students: 9
Failed Students: 1

## Task 9: NumPy Analysis

**Problem Statement:** Compute total, average, highest, lowest marks, and standard deviation using NumPy.

**Approach:** Convert marks list into `numpy.array` to use vectorized functions `np.sum`, `np.mean`, `np.max`, `np.min`, `np.std`.

In [13]:
import numpy as np

marks_array = np.array(all_marks)

total_marks_np = np.sum(marks_array)
average_marks_np = np.mean(marks_array)
highest_marks_np = np.max(marks_array)
lowest_marks_np = np.min(marks_array)
std_marks_np = np.std(marks_array)

print(f"Total Marks: {total_marks_np}")
print(f"Average Marks: {round(average_marks_np, 2)}")
print(f"Highest Marks: {highest_marks_np}")
print(f"Lowest Marks: {lowest_marks_np}")
print(f"Standard Deviation: {round(std_marks_np, 2)}")

Total Marks: 768
Average Marks: 76.8
Highest Marks: 95
Lowest Marks: 39
Standard Deviation: 17.1

## Task 10: Pandas Data Analysis

**Problem Statement:** Load `students.csv` into a DataFrame and explore its structure.

**Approach:** Use `pd.read_csv()` then `.head()`, `.tail()`, `.shape`, `.columns`, `.info()`, `.describe()`.

In [14]:
import pandas as pd

df = pd.read_csv("students.csv")

print("First five rows:")
display(df.head())

print("\nLast five rows:")
display(df.tail())

print("\nDataset shape (rows, columns):", df.shape)
print("\nColumn names:", list(df.columns))

print("\nInfo (data types, non-null counts):")
df.info()

print("\nStatistical summary (numeric columns):")
display(df.describe())

First five rows:

   Student_ID   Name  Age     City        Course  Marks  Attendance_Percentage
0           1  Rahul   22    Patna        Python     85                     92
1           2  Priya   24    Delhi  Data Science     92                     88
2           3   Aman   21  Kolkata        Python     76                     81
3           4   Neha   23   Mumbai     Analytics     88                     95
4           5  Rohan   25    Patna        Python     69                     72

Last five rows:

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
5,6,Simran,22,Delhi,Data Science,91,89
6,7,Vikash,24,Patna,Analytics,55,68
7,8,Pooja,21,Kolkata,Python,78,84
8,9,Arjun,23,Mumbai,Data Science,39,60
9,10,Sneha,22,Delhi,Python,95,97

Dataset shape (rows, columns): (10, 7)

Column names: ['Student_ID', 'Name', 'Age', 'City', 'Course', 'Marks', 'Attendance_Percentage']

Info (data types, non-null counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10 non-null     int64
 1   Name                   10 non-null     object
 2   Age                    10 non-null     int64
 3   City                   10 non-null     object
 4   Course                 10 non-null     object
 5   Marks                  10 non-null     int64
 6   Attendance_Percentage  10 non-null     int64
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

Statistical summary (numeric columns):

       Student_ID        Age      Marks  Attendance_Percentage
count    10.00000  10.000000  10.000000              10.000000
mean      5.50000  22.700000  76.800000              82.600000
std       3.02765   1.337494  18.023442              12.294534
min       1.00000  21.000000  39.000000              60.000000
25%       3.25000  22.000000  70.750000              74.250000
50%       5.50000  22.500000  81.500000              86.000000
75%       7.75000  23.750000  90.250000              91.250000
max      10.00000  25.000000  95.000000              97.000000

## Task 11: Pandas Filtering

**Problem Statement:** Extract subsets: marks > 80, attendance < 75%, from Patna, Python course, failed students.

**Approach:** Use boolean indexing `df[condition]` to keep only matching rows.

In [15]:
above_80 = df[df["Marks"] > 80]
low_attendance = df[df["Attendance_Percentage"] < 75]
from_patna = df[df["City"] == "Patna"]
python_students = df[df["Course"] == "Python"]
failed = df[df["Marks"] < 40]

print("Students who scored more than 80 marks:")
display(above_80)

print("\nStudents whose attendance is below 75%:")
display(low_attendance)

print("\nStudents from Patna:")
display(from_patna)

print("\nStudents enrolled in Python course:")
display(python_students)

print("\nStudents who failed:")
display(failed)

Students who scored more than 80 marks:

   Student_ID    Name  Age    City        Course  Marks  Attendance_Percentage
0           1   Rahul   22   Patna        Python     85                     92
1           2   Priya   24   Delhi  Data Science     92                     88
3           4    Neha   23  Mumbai     Analytics     88                     95
5           6  Simran   22   Delhi  Data Science     91                     89
9          10   Sneha   22   Delhi        Python     95                     97

Students whose attendance is below 75%:

   Student_ID    Name  Age    City        Course  Marks  Attendance_Percentage
4           5   Rohan   25   Patna        Python     69                     72
6           7  Vikash   24   Patna     Analytics     55                     68
8           9   Arjun   23  Mumbai  Data Science     39                     60

Students from Patna:

   Student_ID    Name  Age   City     Course  Marks  Attendance_Percentage
0           1   Rahul   22  Patna     Python     85                     92
4           5   Rohan   25  Patna     Python     69                     72
6           7  Vikash   24  Patna  Analytics     55                     68

Students enrolled in Python course:

   Student_ID   Name  Age     City  Course  Marks  Attendance_Percentage
0           1  Rahul   22    Patna  Python     85                     92
2           3   Aman   21  Kolkata  Python     76                     81
4           5  Rohan   25    Patna  Python     69                     72
7           8  Pooja   21  Kolkata  Python     78                     84
9          10  Sneha   22    Delhi  Python     95                     97

Students who failed:

   Student_ID   Name  Age    City        Course  Marks  Attendance_Percentage
8           9  Arjun   23  Mumbai  Data Science     39                     60

## Task 12: Pandas Sorting

**Problem Statement:** Sort by Marks (desc), Attendance (desc), Name (alphabetical).

**Approach:** Use `.sort_values(by=column, ascending=...)`.

In [16]:
sorted_by_marks = df.sort_values(by="Marks", ascending=False)
sorted_by_attendance = df.sort_values(by="Attendance_Percentage", ascending=False)
sorted_by_name = df.sort_values(by="Name")

print("Sorted by Marks (descending):")
display(sorted_by_marks)

print("\nSorted by Attendance (descending):")
display(sorted_by_attendance)

print("\nSorted by Name (alphabetical):")
display(sorted_by_name)

Sorted by Marks (descending):

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
9,10,Sneha,22,Delhi,Python,95,97
1,2,Priya,24,Delhi,Data Science,92,88
5,6,Simran,22,Delhi,Data Science,91,89
3,4,Neha,23,Mumbai,Analytics,88,95
0,1,Rahul,22,Patna,Python,85,92
7,8,Pooja,21,Kolkata,Python,78,84
2,3,Aman,21,Kolkata,Python,76,81
4,5,Rohan,25,Patna,Python,69,72
6,7,Vikash,24,Patna,Analytics,55,68
8,9,Arjun,23,Mumbai,Data Science,39,60

Sorted by Attendance (descending):

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
9,10,Sneha,22,Delhi,Python,95,97
3,4,Neha,23,Mumbai,Analytics,88,95
0,1,Rahul,22,Patna,Python,85,92
5,6,Simran,22,Delhi,Data Science,91,89
1,2,Priya,24,Delhi,Data Science,92,88
7,8,Pooja,21,Kolkata,Python,78,84
2,3,Aman,21,Kolkata,Python,76,81
4,5,Rohan,25,Patna,Python,69,72
6,7,Vikash,24,Patna,Analytics,55,68
8,9,Arjun,23,Mumbai,Data Science,39,60

Sorted by Name (alphabetical):

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage
2,3,Aman,21,Kolkata,Python,76,81
8,9,Arjun,23,Mumbai,Data Science,39,60
3,4,Neha,23,Mumbai,Analytics,88,95
7,8,Pooja,21,Kolkata,Python,78,84
1,2,Priya,24,Delhi,Data Science,92,88
0,1,Rahul,22,Patna,Python,85,92
4,5,Rohan,25,Patna,Python,69,72
5,6,Simran,22,Delhi,Data Science,91,89
9,10,Sneha,22,Delhi,Python,95,97
6,7,Vikash,24,Patna,Analytics,55,68

## Task 13: Add New Columns

**Problem Statement:** Add `Result`, `Grade`, `Attendance_Status` columns.

**Approach:** Reuse rule functions, apply row-wise using `.apply()`.

In [17]:
def result_col(marks):
    return "Pass" if marks >= 40 else "Fail"

def grade_col(marks):
    if marks >= 90:
        return "A+"
    elif marks >= 75:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 40:
        return "C"
    else:
        return "Fail"

def attendance_status_col(att):
    return "Eligible" if att >= 75 else "Low Attendance"

df["Result"] = df["Marks"].apply(result_col)
df["Grade"] = df["Marks"].apply(grade_col)
df["Attendance_Status"] = df["Attendance_Percentage"].apply(attendance_status_col)

display(df)

,Student_ID,Name,Age,City,Course,Marks,Attendance_Percentage,Result,Grade,Attendance_Status
0,1,Rahul,22,Patna,Python,85,92,Pass,A,Eligible
1,2,Priya,24,Delhi,Data Science,92,88,Pass,A+,Eligible
2,3,Aman,21,Kolkata,Python,76,81,Pass,A,Eligible
3,4,Neha,23,Mumbai,Analytics,88,95,Pass,A,Eligible
4,5,Rohan,25,Patna,Python,69,72,Pass,B,Low Attendance
5,6,Simran,22,Delhi,Data Science,91,89,Pass,A+,Eligible
6,7,Vikash,24,Patna,Analytics,55,68,Pass,C,Low Attendance
7,8,Pooja,21,Kolkata,Python,78,84,Pass,A,Eligible
8,9,Arjun,23,Mumbai,Data Science,39,60,Fail,Fail,Low Attendance
9,10,Sneha,22,Delhi,Python,95,97,Pass,A+,Eligible

## Task 14: Grouping and Aggregation

**Problem Statement:** City-wise/course-wise counts, avg marks by course, avg attendance by city, highest marks per course.

**Approach:** Use `.groupby()` with `.size()`, `.mean()`, `.max()`.

In [18]:
city_counts = df.groupby("City").size()
course_counts = df.groupby("Course").size()
avg_marks_course = df.groupby("Course")["Marks"].mean()
avg_attendance_city = df.groupby("City")["Attendance_Percentage"].mean()
highest_marks_course = df.groupby("Course")["Marks"].max()

print("Students city-wise:")
print(city_counts)

print("\nStudents course-wise:")
print(course_counts)

print("\nAverage marks course-wise:")
print(avg_marks_course)

print("\nAverage attendance city-wise:")
print(avg_attendance_city)

print("\nHighest marks in each course:")
print(highest_marks_course)

Students city-wise:
City
Delhi      3
Kolkata    2
Mumbai     2
Patna      3
dtype: int64

Students course-wise:
Course
Analytics       2
Data Science    3
Python          5
dtype: int64

Average marks course-wise:
Course
Analytics       71.5
Data Science    74.0
Python          80.6
Name: Marks, dtype: float64

Average attendance city-wise:
City
Delhi      91.333333
Kolkata    82.500000
Mumbai     77.500000
Patna      77.333333
Name: Attendance_Percentage, dtype: float64

Highest marks in each course:
Course
Analytics       88
Data Science    92
Python          95
Name: Marks, dtype: int64

## Task 15: Final Mini Project Report

**Problem Statement:** Produce a consolidated summary and save the final dataset as `final_student_performance_report.csv`.

**Approach:** Compute metrics from the enriched DataFrame, assemble a summary table, and export with `.to_csv()`.

In [19]:
total_students_f = len(df)
average_marks_f = round(df["Marks"].mean(), 2)
highest_marks_f = df["Marks"].max()
lowest_marks_f = df["Marks"].min()
passed_students_f = (df["Result"] == "Pass").sum()
failed_students_f = (df["Result"] == "Fail").sum()
low_attendance_f = (df["Attendance_Status"] == "Low Attendance").sum()
above_80_f = (df["Marks"] > 80).sum()

final_report = pd.DataFrame({
    "Metric": [
        "Total Students", "Average Marks", "Highest Marks", "Lowest Marks",
        "Passed Students", "Failed Students", "Students with Low Attendance",
        "Students Scoring Above 80"
    ],
    "Value": [
        total_students_f, average_marks_f, highest_marks_f, lowest_marks_f,
        passed_students_f, failed_students_f, low_attendance_f, above_80_f
    ]
})

display(final_report)

df.to_csv("final_student_performance_report.csv", index=False)
print("\nfinal_student_performance_report.csv saved successfully.")

                         Metric  Value
0                Total Students   10.0
1                 Average Marks   76.8
2                 Highest Marks   95.0
3                  Lowest Marks   39.0
4               Passed Students    9.0
5               Failed Students    1.0
6  Students with Low Attendance    3.0
7     Students Scoring Above 80    5.0

final_student_performance_report.csv saved successfully.

## Deliverables Generated

Running this notebook top-to-bottom produces:
- `students.csv` — raw dataset (Task 8)
- `student_summary.txt` — plain-text summary (Task 7)
- `final_student_performance_report.csv` — enriched dataset (Task 15)